### ISSUE TITLE
Impossible to call pystress from Python

### ISSUE THREAD

**Issue by metaperl** [shichao-an/pystress#2]
The [current main function in pystress](https://github.com/shichao-an/pystress/blob/master/pystress.py#L57)  is designed for command-line usage of `pystress` . There is no support for invoking the functionality of `pystress` from a Python program, e.g: `pystress.stress(exec_time, proc_num)`.

I propose a refactoring of `_main` for this purpose.

**Comment by shichao-an** [comment]
This has been fixed in #3
